### ISSUE TITLE
Cannot find textures.json

### ISSUE THREAD

**Issue by Syndaryl** [YSelfTool/MapRend#3]
Windows 7, Java 1.8, using the precompiled JAR

I have copied the block texture assets to the ressource\raw subdirectory and I try to generate the colors.json but get the following error:

D:\Games\MapRend>java -jar MapRend.jar textures ressource
MapRend Texture Rendering startup messages
Ressource folder: ressource
Stopping: Cannot find textures.json!

However, there is a textures.json in the same folder as my MapRend.jar - it is the one that comes with the precompiled JAR?
Do I need to relocate it somewhere?

**Comment by YSelfTool** [comment]
Yes, you need to relocate textures.json from the folder with the precompiled .jar to the ressource/-directory.
