### ISSUE TITLE
all-white png on 2nd run

### ISSUE THREAD

**Issue by jfbarras** [YSelfTool/MapRend#4]
When choosing to let the application render clusters, ie
map <worldfolder> . . day 50 rect cluster ./maps .
the 2nd of two sequential executions will produce an all-white overall png.
The application will report
   Succesfully read updates.json file with 4 elements!
   Saved updates.json file (4 elements) !
   Successfully written image to <outputfile>
   Needed 530
   Updated 0 of 4 regions!
But will overwrite outputfile will all-white data.

**Comment by YSelfTool** [comment]
Should be fixed with last commit.
Now it reuses the existing big file if possible or redraws everything if the file does not fit/exist.

**Comment by jfbarras** [comment]
Great!

**Comment by YSelfTool** [comment]
One more change: Reusing an image based on the age of updates.json, not the age of the image, could lead to reusing too old images. So now there is an updates.json per image, not simply one for all images in that folder.

**Comment by jfbarras** [comment]
Aren't you worried about the number of json files? Instead of having a file per image, why not have a time stamp per image (and data per image) in the same updates.json file?

**Comment by YSelfTool** [comment]
Not really, I'd rather have two .json-files per world than one monolithic file for all the worlds.
