### ISSUE TITLE
should use default biome on null biome

### ISSUE THREAD

**Issue by jfbarras** [YSelfTool/MapRend#5]
It happens that the biomColors array is hollow, ie has holes. So, as much as it is interesting to use the default biome on ArrayIndexOutOfBoundsException, it should also do that on null, as follows:

```
    try {
        color = biomColors[biome];
        if (color == null) {
            System.out.println("Null biome: " + biome + ", copying default: 1.");
            biomColors[biome] = biomColors[1];
            color = biomColors[1];
        }
    } catch (...)
```

**Comment by jfbarras** [comment]
See pull
https://github.com/YSelfTool/MapRend/pull/8
for this.

**Comment by YSelfTool** [comment]
Pull request is merged.

**Comment by jfbarras** [comment]
Cool.
