### ISSUE TITLE
should assume not visible when block not listed

### ISSUE THREAD

**Issue by jfbarras** [YSelfTool/MapRend#6]
The level will sometimes have block types that weren't planned for, ie not listed in the json files. Instead of letting those popup as NullPointerExceptions, one should maybe assume they are not visible, as follows:

```
private boolean isBlockSolid(int block) {
    try {   
        return Program.blockVisibility[block];
    } catch (ArrayIndexOutOfBoundsException aioobe) {
        //XXX assumes that block is invisible if not listed
        return false;
    }
}
```

**Comment by jfbarras** [comment]
See pull
https://github.com/YSelfTool/MapRend/pull/9
for this

**Comment by YSelfTool** [comment]
Is merged, thanks.

**Comment by jfbarras** [comment]
No problem!
